<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <PackageId>EFCore.SoftAudit</PackageId>
        <Version>1.0.0</Version>
        <Authors>Maksym Chmel</Authors>
        <Description>Automatic soft delete and audit fields for EF Core entities</Description>
        <PackageTags>efcore;softdelete;audit;entityframework</PackageTags>
        <RepositoryUrl>https://github.com/maksim-chmel/EFCore.SoftAudit</RepositoryUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="samples/**"/>
        <None Remove="samples/**"/>
        <Content Remove="samples/**"/>
        <EmbeddedResource Remove="samples/**"/>
        <Compile Remove="tests/**"/>
        <None Remove="tests/**"/>
        <Content Remove="tests/**"/>
        <EmbeddedResource Remove="tests/**"/>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.2.0" />
      <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.0" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    </ItemGroup>

</Project>
